### ISSUE TITLE
What do I do now?

### ISSUE THREAD

**Issue by Zaydiscool777** [Anon23261/GHOSTc-OS#1]
i don’t have a pi or a flipper, so i can’t really do anything.

**Comment by Anon23261** [comment]
I actually built this on a desktop used code::blocks and the arm project. It still has a bunch of issues though

**Comment by Zaydiscool777** [comment]
What should I start working on?

**Comment by Anon23261** [comment]
Help me fix and find any issues in my code please.

**Comment by Zaydiscool777** [comment]
Okay. BTW, you can assign me to issue whenever you like. Also, i’ll create a branch now.

**Comment by Zaydiscool777** [comment]
*pull request, can’t create a branch. It’s okay, though.

**Comment by evjf** [comment]
I forgot to say I use this account for pull requests. Sorry.
